### PR TITLE
feat: Add back SSL support for MariaDB 5.5.68

### LINKED ISSUE #336: 1.3.2 build fails
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Session log attached.

```r
# insert reprex here
```
[RMariaDB.txt](https://github.com/user-attachments/files/15569053/RMariaDB.txt)

### PR DESCRIPTION
**Pull request by d-hansen**
Add back SSL support for MariaDb 5.5.68 which seems to be the default MariaDB version in AWS AL2 base.

Note: AWS AL2 will be deprecated and replaced by AL2023 in June 2025.
Note<sup>2</sup>: At some point in the future, I would expect some version of MariaDB (> 11) to follow suit with MySQL 8 and switch to using the `MYSQL_OPT_SSL_MODE` instead of `MYSQL_OPT_SSL_ENFORCE` to enable SSL.

Closes #336.

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks for the super-quick fix. How can we test this in CI/CD?

**Comment by d-hansen** [comment]
mariadb-libs-5.5.68 is still generally available: https://rpmfind.net/linux/RPM/centos/7.9.2009/x86_64/Packages/mariadb-libs-5.5.68-1.el7.x86_64.html
I'm not sure what system you are using to host your CI/CD, but probably just make an docker container that includes that version of the MariaDb libraries.

**Comment by d-hansen** [comment]
FYI: this archive includes the -devel package:
https://archive.mariadb.org/mariadb-5.5.68/yum/rhel/6Server/x86_64/rpms/

**Comment by d-hansen** [comment]
Well, I see you run Ubuntu 22.   So, here is a link you can download MariaDb 5.5.68 for a systemd-based Linux:
https://archive.mariadb.org/mariadb-5.5.68/bintar-linux-systemd-x86_64/mariadb-5.5.68-linux-systemd-x86_64.tar.gz
That's the full server enchilada, so should be more than enough to test with.

**Comment by krlmlr** [comment]
Thanks. I want to add old MariaDB to CI/CD before merging this.

@BillWeld: Can you please confirm that this PR works for you?

**Comment by BillWeld** [comment]
I don’t know how to grab that version. I can specify releases by git tag if there’s a tag you can point me to.

**Comment by krlmlr** [comment]
@BillWeld: Can you please 

```r
install_github("r-dbi/RMariaDB#338")
```

or

```r
install_github("d-hansen/RMariaDB")
```

?

**Comment by BillWeld** [comment]
Will do. On Jul 7, 2024, at 4:22 PM, Kirill Müller ***@***.***> wrote:﻿
@BillWeld: Can you please
install_github("r-dbi/RMariaDB#338")
or
install_github("d-hansen/RMariaDB")
?

**Comment by BillWeld** [comment]
Both build cleanly.

Thanks,
Rob

**Comment by d-hansen** [comment]
Hey, I noticed this PR is still outstanding. Any update on merging it?  Anything you need from me?

**Comment by krlmlr** [comment]
Thanks. Taking care of the failing builds in #344.

**Comment by krlmlr** [comment]
Thanks, also for the nudge!

**Pull request merged**
