### PR TITLE
Upgrade libmariadbclient on Windows

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by krlmlr** [comment]
Wow, that was fast. Thanks!

Does this drop support for R 3.1? I haven't tested R 3.1, but it *might* work ;-)

**Comment by jeroen** [comment]
I'm not testing anymore with the old toolchain. Is that a requirement?

**Comment by jeroen** [comment]
It seems to build fine but some unit test are broken on master. Perhaps you should fix this first?

**Comment by jeroen** [comment]
I have added zlib to the libmariadb rwinlib bundle so I think it should work with the old toolchain. But I don't have a box setup to test R 3.1.

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
